M48
; DRILL file {KiCad 6.0.9-8da3e8f707~116~ubuntu22.04.1} date qui 01 dez 2022 16:18:18
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-12-01T16:18:18-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.9-8da3e8f707~116~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X53.5Y-54.5
X53.5Y-104.5
X118.5Y-54.5
X118.5Y-104.5
T0
M30
